spring:
  ai:
    mcp:
      server:
        name: Mcp-Server-Local   # MCP服务名称
        version: 2.0.0            # 服务版本
        type: ASYNC                # 调用类型：SYNC（同步）或ASYNC（异步）
        instructions: "本地MCP服务，用于测试和开发目的，包括天气查询工具"
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 10000
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        protocol: streamable
    alibaba:
      mcp:
        nacos:
          namespace: mcp
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          register:
            enabled: true
#            service-group: mcp-server
            service-name: webflux-mcp-server-yingzi