server:
  port: 11311
spring:
  ai:
    dashscope:
      chat:
        api-key: ${DASHSCOPE_CHAT_KEY}
#    ollama:
#      base-url: http://localhost:11434
#      chat.model: qwen3:8b
  config:
    import:
      - optional:classpath:.env[.properties]
