server:
  port: 8085

spring:
  config:
    import:
     - classpath:config/mcp-server.yml
  application:
    name: mcp-server


# 添加调试日志
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.mcp: DEBUG