seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${SEATA_GROUP}
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  service:
    vgroup-mapping:
      tx_jk_group: default
    grouplist:
      default: ${SEATA_GROUP_LIST}
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: file