spring:
  kafka:
    bootstrap-servers: localhost:9192
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
    admin:
      auto-create: true