server:
  port: 17006
spring:
  application:
    name: ndpa-process
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: ${DB_ENGINE:mysql}
  config:
    import:
      - classpath:config/minio.yml


logging:
  config: classpath:log4j2/log4j2-spring-local.xml
