spring:
  alibaba:
    mcp:
      nacos:
        client:
          enabled: true
          sse:
            connections:
              server1:
                service-name: Mcp-Server-Local # Nacos 中对应 MCP Server 的服务名
                version: 1.0.0 # Nacos 中对应 MCP Server 的版本号
          configs:
            server1:
              namespace: 4ad3108b-4d44-43d0-9634-3c1ac4850c8c
              server-addr: 127.0.0.1:8848
              username: nacos
              password: nacos
#        nacos:
#          namespace: public
#          server-addr: 127.0.0.1:8848
#          username: nacos
#          password: nacos
#          client:
#            enabled: true
#            sse:
#              connections:
#                server1:
#                  service-name:
#                  version: 1.0.0
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client-webflux
        version: 0.0.1
        initialized: true
        request-timeout: 600s
        type: async
        toolcallback:
          enabled: true
        root-change-notification: true