spring:
  ai:
    mcp:
      server:
        type: ASYNC
        name: book-mcp-server
        version: "1.0.0"
        base-url: http://localhost:8085
        enabled: true
        sse-message-endpoint: /sse
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false